development:
 adapter: mysql2
 database: developmentdb
 username: root
 password: password
 host: localhost
 encoding: utf8

test:
 database: testdb
 adapter: mysql2
 encoding: utf8
 username: root
 password: password
 host: localhost

production:
 adapter: mysql2
 database: Railsdb
 username: root
 password: password
 host: localhost
 encoding: utf8